import createFetchClient, { Middleware } from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript
import { authTokenStorage } from "./auth-storage";

const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:4137",
});

const authMiddleware: Middleware = {
  async onRequest({ request, options }) {
    const token = await authTokenStorage.getValue();
    request.headers.set("Authorization", token ? `Bearer ${token}` : "");
    return request;
  },
};
fetchClient.use(authMiddleware);
export const $api = createClient(fetchClient);
